name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build
        run: |
          npm ci
          composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SLUG: "menu-icons"
          SVN_PASSWORD: ${{ secrets.SVN_THEMEISLE_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_THEMEISLE_USERNAME }}
